#!/bin/bash
#

LOGFILE='ned.log'
RESPONSE=$(curl http://fom.londondroids.com/index.php/api/fetch_stamat_entities/limit/100)
echo $RESPONSE > $LOGFILE
cat $LOGFILE | mail -s "STAMAT named entities extraction" thomasalisi@gmail.com
rm -f $LOGFILE
